### PR TITLE
more css works

### PR DESCRIPTION
**Pull request by piwats**
1.) Redesign of the login page
2.) Navbar using foundation5, searchbox in navbar (the clear button inside the searchbox has to be modified, looks displaced at the moment)
2.) add option to hide slave-zones, e.g. $showslavezones, line 170

### CODE REVIEW

**Comment by tuxis-ie** [comment]
Thanks for your efforts. Three requests:
1. Can you fix indenting to use four spaces per tab?
2. Screenshots?
3. Github says there are conflicts. Can you fix those?

**Comment by piwats** [comment]
will correct all of the points on the weekend.

**Comment by HLFH** [comment]
cc @piwats Nice weekend.

**Comment by Faizan200** [comment]
hi.. i'm new to handle power dns. i'm trying to use NSEDIT first time i'm facing problem regarding apikey,pass,vers please help me to get these values. someone is here to guide me to get these values

**Comment by HLFH** [comment]
@Faizan200 If you are you to PowerDNS, it would be simpler for you to use `pdnsutil` instead of `nsedit`. https://blog.powerdns.com/2016/02/02/powerdns-authoritative-the-new-old-way-to-manage-domains/

**Pull request closed without merging**
