### PR TITLE
dynamic NS-entry config and https support

### PR DESCRIPTION
**Pull request by bfbones**
Hello,

sorry for the last stupid commit, it was to late at night.

I added the abbility to insert multiple dns-servers for NS-field generation for setups with 3 or more nameserver.
I also added a config-parameter to call the API via https.

### CODE REVIEW

**Comment by tuxis-ie** [comment]
Hi, that looks userful. However, I just changed the javascript handling nameservers for templates. Could you try to fit this feature in the new situation?

**Comment by bfbones** [comment]
Sure, I can to that this evening.
Problem is that I have to update my powerdns due to it's still version 3.4.1 which doesn't work with your newest changes.

**Comment by Finkregh** [comment]
is this already merged? or why is this issue closed?

**Comment by bfbones** [comment]
opened a new request due to my tree was outdated.

**Comment by Finkregh** [comment]
this one, i suppose? https://github.com/tuxis-ie/nsedit/pull/34
you might want to reference the new one in the future or just update this one ;)

**Comment by bfbones** [comment]
sorry.
see #34

**Pull request closed without merging**
