### PR TITLE
Updated readme and config.inc.php-dist regarding #172

### PR DESCRIPTION
**Pull request by margau**

### CODE REVIEW

**Comment by tuxis-ie** [comment]
Great. There are some checks in misc.inc.php. Can we actively check if this file is readable via the web and warn people about it?

**Comment by margau** [comment]
I'll look into this and try it out.

**Comment by margau** [comment]
Hello, maybe we should do this check asynchronously on the client side. 
Opinions?

**Comment by tuxis-ie** [comment]
Might be easier, yes.

**Pull request merged**
