### PR TITLE
Remove priority field

### PR DESCRIPTION
**Pull request by zeha**
It's gone from PowerDNS 3.4.2 and later.

### CODE REVIEW

**Comment by zeha** [comment]
Haven't actually tried this out (don't have a php server at hand).

**Comment by Genesis2001** [comment]
Works with pdns 3.4.1 now. Was getting a "An error occured while communicating with the server" error popup with nothing else.

**Comment by Genesis2001** [comment]
Actually, I have noticed now, that I can't edit records because I now get:

"API Error 422: Key 'priority' not an Integer or not present"

PDNS 3.4.1, however, it did fix the other error I had (mentioned above).

**Comment by tuxis-ie** [comment]
Ok, so this breaks 3.4.1, we'd need to figure out a way to prevent that.

**Pull request merged**
