### PR TITLE
added initial https support

### PR DESCRIPTION
**Pull request by seitzbg**
Adjust as needed.

### CODE REVIEW

**Comment by piwats** [comment]
This brings some errors about apiproto in zones.php

```
PHP message: PHP Notice:  Undefined variable: apiproto in /var/www/nsedit/zones.php on line 16
PHP message: PHP Notice:  Undefined variable: apiproto in /var/www/nsedit/zones.php on line 21
PHP message: PHP Notice:  Undefined variable: apiproto in /var/www/nsedit/zones.php on line 26" while reading response header from upstream, client: xx.xx.xx.xx, server: hello.foo, request: "POST /nsedit/zones.php?action=listslaves&jtStartIndex=0&jtPageSize=20 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.socket:", host: "hello.foo", referrer: "https://hello.foo/nsedit/index.php"
````

**Comment by piwats** [comment]
The last commit fixed the apiproto-error, but now there is

"The value for $apisslverify is incorrect in your config. Did you configure it?"

Even if $apisslverify = FALSE; is set - without the typo.

**Comment by tuxis-ie** [comment]
Ah, the patch checks for /[01]/. I'll make it test for TRUE/FALSE as well.. Sorry.

**Comment by piwats** [comment]
Do you have to add $apiproto to the globals in line 16 of zones.php?

```
...
function api_request($path, $opts = null, $type = null) {
    global $apisid, $apiuser, $apipass, $apiip, $apiport, $apiproto, $authmethod;
...
```

**Comment by tuxis-ie** [comment]
No, in config .php

-- 
Mark Schouten
Tuxis Internet Engineering
mark@tuxis.nl / 0318 200208

**Comment by piwats** [comment]
$apiproto = 'http'; is set in config.inc.php

What I meant was, that if $apiproto is not present in line 16 of zones.php, then I get an "Api Error 0".

**Comment by piwats** [comment]
Was closed in #45.

**Pull request merged**
