### PR TITLE
Ability to rotate logs

### PR DESCRIPTION
**Pull request by richard-underwood**
This is for #107 - the core work is complete, but it needs testing, particularly with a mix of unusual logging and allow*logs options.

Please don't merge yet, but let me know if you have any comments.

### CODE REVIEW

**Comment by richard-underwood** [comment]
What is the minimum version of PHP for this project? I noticed that curl_reset is used in includes/class/ApiHandler.php which is PHP 5.5. I'm currently running on 5.6, but don't want to add anything which will conflict - e.g. CentOS 7 has PHP 5.4 as standard.

**Comment by richard-underwood** [comment]
This pull request has an unrelated test for curl_reset (for PHP <= 5.4) in it. Let me know if you'd like this taken out of this branch.

**Comment by tuxis-ie** [comment]
Would be great if you could make it an extra PR to make nsedit better working for other users as well!

**Comment by richard-underwood** [comment]
Done.

**Comment by richard-underwood** [comment]
I'm done (for now!) I've tested as much as possible, and all looks good to me. Let me know if you see any issues or have changes you'd like to make.

**Pull request merged**
