### PR TITLE
notify pdns after zone update

### LINKED ISSUE #165: notify pdns after zone update
Possibility to enable notification via API when a change is made on a zone

### PR DESCRIPTION
**Pull request by Rico29**
fix #165

### CODE REVIEW

**Comment by tuxis-ie** [comment]
Looks good. Thanks.

**Comment by tuxis-ie** [comment]
I missed something. $notifyafterupdate is not set anywhere and thus will cause a lot of ``PHP Notice:  Undefined variable``/. Can you fix that please?

**Comment by HLFH** [comment]
@tuxis-ie Sending a DNS NOTIFY to all slaves can be done at the `pdns` level without these commits. Is this PR needed?

**Comment by tuxis-ie** [comment]
Well, this tells pdns to do the notify. What would you suggest?

**Comment by HLFH** [comment]
Raising the serial number of a domain suffices to trigger PowerDNS to send out notifications. When a zone is updated in master, the serial of the zone changes, therefore, the master sends a NOTIFY to the slave. I think this code is duplicating NOTIFY requests.

**Pull request merged**
